### ISSUE TITLE
Windows10で動作しない

### ISSUE THREAD

**Issue by Xi80** [chitoku-k/NowPlayingLib#1]
# 発生している問題

Windows10上でサンプル含めSystem.NotSupportedExceptionを吐き動作しない。

![image](https://user-images.githubusercontent.com/54576108/147530148-f603357b-645b-430e-b97c-5ac3b227d5a4.png)

# 環境

Windows10 21H1
WMP 12/Foobar2k 1.6.7

**Comment by Xi80** [comment]
もう一度試してみたところFoobar2000では動作しましたがWMPでは動作しませんでした。

**Comment by chitoku-k** [comment]
System.NotSupportedException のスタックトレースをお願いします。また、アルバムアートワークのある曲とない曲で例外の発生状況に変化があるかもためしてみてください。

**Comment by chitoku-k** [comment]
System.NotSupportedException は確認できませんでしたが Windows Media Player でアルバムアートワークが取得できない場合に曲自体の情報が取得できなくなる問題を修正した [v1.5.0.0](https://github.com/chitoku-k/NowPlayingLib/releases/tag/1.5.0.0) をリリースしました

**Comment by Xi80** [comment]
https://github.com/chitoku-k/NowPlayingLib/blob/a8c86135866fb2ba78408d3ded212631f32e4da2/NowPlayingLib/MediaPlayerBase.cs#L41

CDを再生していたためpathが"wmpcd://0/1"となっていたことが原因でした。
お手数をおかけしました。
